name: Metrics
env:
  TOKEN: ${{ secrets.PERSONAL_TOKEN }}
on:
  # Schedule daily updates
  schedule: [{cron: "0 0 * * *"}]
  # (optional) Run workflow manually
  workflow_dispatch:
  # (optional) Run workflow when pushing on master/main
  push: {branches: ["master", "main"]}
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ env.TOKEN }}
          plugin_achievements: yes
          plugin_achievements_display: compact
          plugin_stackoverflow: yes
          plugin_stackoverflow_user: 7037861

